#! /bin/sh

PANEL_FIFO=/tmp/panel-fifo
PANEL_DIR=~/.config/bspwm/panel

. config

if [ $(pgrep -cx panel) -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT
bspc control --subscribe > "$PANEL_FIFO" &
#echo "T" >  "$PANEL_FIFO" &
conky -c $PANEL_DIR/panel_conky > "$PANEL_FIFO" &
./notify_mpd -d &

cat "$PANEL_FIFO" \
	| panel_bar \
	| bar \
		-f "$FONT1","$FONT2"\
		-F "$COLOR_FOREGROUND"\
		-B "$COLOR_BACKGROUND"\
		-g "$PANEL_GEOMETRY"\
		-u $LINEHEIGHT &
wait
